import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/partials/Footer";
import { cn } from "@/lib/utils";
import NavBar from "@/components/partials/NavBar";
import QueryProvider from "@/providers/QueryProvider";
import AuthProvider from "./auth/Provider";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lensart Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "overflow-x-hidden")}>
        <QueryProvider>
          <AuthProvider>
            <NavBar />
            {children}
            <Footer />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
